# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Pay-As-You-Go(2)(79c65e59-aadb-45ab-9a43-3e10d9e5225e)'
    backendAzureRmResourceGroupName: 'friday-rg'
    backendAzureRmStorageAccountName: 'friday2102'
    backendAzureRmContainerName: 'friday-cont'
    backendAzureRmKey: 'my-terraform.tfstate'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Pay-As-You-Go(3)(79c65e59-aadb-45ab-9a43-3e10d9e5225e)'